### ISSUE TITLE
Item name cut off at ampersand (&)

### ISSUE THREAD

**Issue by Lackmake** [webD97/rewe-ebon-parser#5]
Hi,

the parser seems to have a problem with an ampersand "&" in the product name. I had the item "BUD & TERENCE" on my ebon
What i received back from the parser was " TERENCE" (notice the leading space).

Edit: Had a short look, it probably just needs an adjustment of the regex in [line 38](https://github.com/webD97/rewe-ebon-parser/blob/a4182732072e7c1bf3b304225b3e1656a3acb904/src/index.ts#L38)

**Comment by webD97** [comment]
Thank you for reporting this issue! I will take a look at it.

**Comment by webD97** [comment]
I added the ampersand to the regex in the master branch and tested the regex in regex101.com - Would it be possible for you to test against the latest master?

**Comment by Lackmake** [comment]
Yes, tested sucessfully, thanks

**Comment by webD97** [comment]
Great, thank you! I will create a release as soon as possible.

Am 15.02.2023 08:53 schrieb Lackmake ***@***.***>:

Yes, tested sucessfully, thanks

**Comment by webD97** [comment]
Released with version 0.3.4
